### ISSUE TITLE
eblob_merge segfaults when it merges a lot of blobs

### ISSUE THREAD

**Issue by shaitan** [reverbrain/eblob#120]
```
$ eblob_merge -d -i ./data-00.183 -i ./data-0.167 -i ./data-0.186 -i ./data-0.162 -i ./data-0.176 -i ./data-0.119 -i ./data-0.185 -i ./data-0.196 -i ./data-0.192 -i ./data-0.161 -i ./data-0.160 -i ./data-0.180 -i ./data-0.93 -i ./data-0.182 -i ./data-0.0 -i ./data-0.194 -i ./data-0.114 -i ./data-0.165 -i ./data-0.191 -i ./data-0.163 -i ./data-0.184 -i ./data-0.166 -i ./data-0.178 -i ./data-0.175 -i ./data-0.177 -i ./data-0.174 -i ./data-0.74 -i ./data-0.195 -i ./data-0.7 -i ./data-0.141 -i ./data-0.181 -i ./data-0.197 -i ./data-0.98 -i ./data-0.190 -i ./data-0.193 -i ./data-0.36 -i ./data-0.171 -i ./data-0.54 -i ./data-0.189 -i ./data-0.170 -i ./data-0.156 -i ./data-0.111 -i ./data-0.187 -i ./data-0.144 -i ./data-0.164 -i ./data-0.64 -i ./data-0.173 -i ./data-0.172 -i ./data-0.152
Segmentation fault
```

```
Core was generated by `eblob_merge -d -i ./data-0.186 -i ./data-0.201 -i ./data-0.0 -i ./data-0.180 -i'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f49d23fd030 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007f49d23fd030 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x000000000040a333 in void std::__introsort_loop<__gnu_cxx::__normal_iterator<em_ctl*, std::vector<em_ctl, std::allocator<em_ctl> > >, long, em_compare>(__gnu_cxx::__normal_iterator<em_ctl*, std::vector<em_ctl, std::allocator<em_ctl> > >, __gnu_cxx::__normal_iterator<em_ctl*, std::vector<em_ctl, std::allocator<em_ctl> > >, long, em_compare) ()
#2  0x0000000000404e56 in main ()
(gdb) bt full
#0  0x00007f49d23fd030 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x000000000040a333 in void std::__introsort_loop<__gnu_cxx::__normal_iterator<em_ctl*, std::vector<em_ctl, std::allocator<em_ctl> > >, long, em_compare>(__gnu_cxx::__normal_iterator<em_ctl*, std::vector<em_ctl, std::allocator<em_ctl> > >, __gnu_cxx::__normal_iterator<em_ctl*, std::vector<em_ctl, std::allocator<em_ctl> > >, long, em_compare) ()
No symbol table info available.
#2  0x0000000000404e56 in main ()
No symbol table info available.
```

**Comment by bioothod** [comment]
This needs eblob-dbg package to decode

**Comment by abudnik** [comment]
https://github.com/reverbrain/eblob/pull/123
